name: Build and publish images

on:
    push:
        branches:
            - master

env:
    DOCKER_IMAGE_NAME: ${{ vars.DOCKER_HUB_REPO }}

jobs:
    build-cli:
        name: Build CLI image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USER }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push image to registry
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile.cli
                  push: true
                  tags: |
                      ${{ env.DOCKER_IMAGE_NAME }}:cli
                      ${{ env.DOCKER_IMAGE_NAME }}:cli-${{ github.sha }}
                  cache-from: |
                      type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:cli
                      type=gha,scope=${{ github.workflow }}
                  cache-to: type=gha,scope=${{ github.workflow }},mode=max

    build-fpm:
        name: Build FPM image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USER }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push image to registry
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile.fpm
                  push: true
                  tags: |
                      ${{ env.DOCKER_IMAGE_NAME }}:fpm
                      ${{ env.DOCKER_IMAGE_NAME }}:fpm-${{ github.sha }}
                  cache-from: |
                      type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:fpm
                      type=gha,scope=${{ github.workflow }}
                  cache-to: type=gha,scope=${{ github.workflow }},mode=max

    build-fpm-nginx:
        name: Build FPM NGINX image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USER }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push image to registry
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile.fpm-nginx
                  push: true
                  tags: |
                      ${{ env.DOCKER_IMAGE_NAME }}:fpm-nginx
                      ${{ env.DOCKER_IMAGE_NAME }}:fpm-nginx-${{ github.sha }}
                  cache-from: |
                      type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:fpm-nginx
                      type=gha,scope=${{ github.workflow }}
                  cache-to: type=gha,scope=${{ github.workflow }},mode=max
