name: Build and deploy application

on:
    push:
        branches:
            - master

env:
    DOCKER_IMAGE_NAME: ${{ vars.DOCKER_HUB_REPO }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Copy repository code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USER }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build FPM image
              run: |
                  docker build \
                      -f Dockerfile.fpm \
                      -t ${{ env.DOCKER_IMAGE_NAME }}:8.3-fpm \
                      -t ${{ env.DOCKER_IMAGE_NAME }}:8.3-fpm-${{ github.sha }} \
                      .

            - name: Build CLI image
              run: |
                  docker build \
                      -f Dockerfile.cli \
                      -t ${{ env.DOCKER_IMAGE_NAME }}:8.3-cli \
                      -t ${{ env.DOCKER_IMAGE_NAME }}:8.3-cli-${{ github.sha }} \
                      .

            - name: Push built image to Docker Hub
              run: docker push ${{ env.DOCKER_IMAGE_NAME }} --all-tags
